### ISSUE TITLE
seg fault in BoundedQueue

### ISSUE THREAD

**Issue by davidc** [irrtoolset/irrtoolset#50]
Compiled 5.0.1 on Debian 9 (gcc 6.3.0-18+deb9u1)
Segfaults on the first @RtConfig lines in various inputs that worked on another machine also running 5.0.1, although that one was compiled in 2013.

I don't know if this is enough to see the problem or if I need to try to figure out where it's going wrong and produce a test case:

```Segmentation fault (core dumped)
root@netman08:~/rtconfig# gdb rtconfig core
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from rtconfig...done.
[New LWP 25473]
Core was generated by `rtconfig -f as42579.filtered.private -D 1 -cisco_no_default_afi -cisco_use_pref'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000555739b77081 in BoundedQueue<RadixTree*>::enq (elt=0x0, this=0x555739e11d40 <_ZL6pStack>)
    at Stack.hh:76
76            q[last++] = elt;
(gdb) bt
#0  0x0000555739b77081 in BoundedQueue<RadixTree*>::enq (elt=0x0, this=0x555739e11d40 <_ZL6pStack>)
    at Stack.hh:76
#1  BoundedStack<RadixTree*>::push (elt=0x0, this=0x555739e11d40 <_ZL6pStack>) at Stack.hh:96
#2  RadixTree::insert (this=0x0, _addr=3221554432, _leng=_leng@entry=24, _rngs=_rngs@entry=256)
    at RadixSet.cc:422
#3  0x0000555739b7c6c6 in RadixSet::insert (rngs=256, leng=<optimized out>, addr=<optimized out>,
    this=0x55573a816ef0) at RadixSet.hh:301
#4  SetOfPrefix::insert (this=this@entry=0x55573a816ee8, b=...) at SetOfPrefix.cc:73
#5  0x0000555739b72b05 in SetOfPrefix::operator|= (b=..., this=0x55573a816ee8)
    at SetOfPrefix.hh:107
#6  FilterOfPrefix::operator|= (b=..., this=0x55573a816ee0) at FilterOfPrefix.hh:100
#7  NormalExpression::evaluate (ptree=ptree@entry=0x55573a815ca0, peerAS=peerAS@entry=8330,
    expand=expand@entry=4294967295) at NE.cc:368
#8  0x0000555739b72fbd in NormalExpression::evaluate (ptree=<optimized out>,
    peerAS=peerAS@entry=8330, expand=expand@entry=4294967295) at NE.cc:246
#9  0x0000555739b7491f in NormalExpression::evaluate (ptree=0x55573a7f9210,
    peerAS=peerAS@entry=8330, expand=expand@entry=4294967295) at NE.cc:345
#10 0x0000555739b72daf in NormalExpression::evaluate (ptree=0x55573a811a30,
    peerAS=peerAS@entry=8330, expand=expand@entry=4294967295) at NE.cc:148
#11 0x0000555739b7491f in NormalExpression::evaluate (ptree=ptree@entry=0x55573a813970,
    peerAS=peerAS@entry=8330, expand=expand@entry=4294967295) at NE.cc:345
#12 0x0000555739b4ddf4 in CiscoConfig::importP (this=0x555739e11680 <ciscoConfig>, asno=42579,
    addr=<optimized out>, peerAS=8330, peer_addr=0x55573a7d7330) at f_cisco.cc:1287
#13 0x0000555739b5f068 in commandparse () at command.y:186
#14 0x0000555739b3a0f6 in main (argc=12, argv=0x7ffe5ce35218, envp=0x7ffe5ce35280)
    at rtconfig.cc:280
(gdb)
```

**Comment by nickhilliard** [comment]
5.0.1 is too old. Can you test this out on master and see if the problem persists.  Instructions here:

https://github.com/irrtoolset/irrtoolset/wiki/IRRToolSet-Installation

**Comment by davidc** [comment]
Much better thanks. You should do a new version, I just picked the last release available :)

Underlying cause was the fact that I had patched irrd to surround each record with >< because I was debugging that archaic piece of software last week.

With the latest version it now correctly prints an error instead of segfaulting: "Warning: no end of data line error for query !mfilter-set,FLTR-BOGONS."

Thanks

-davidc
